#!/bin/sh
BASEDIR="."
pip -q install -r $BASEDIR/requirements.txt
curl -s "https://www.post.japanpost.jp/zipcode/dl/kogaki/zip/ken_all.zip" > $BASEDIR/assets/ken_all.zip
(cd $BASEDIR/assets && unzip -qo ./ken_all.zip)
